### ISSUE TITLE
Crashing in PlayerComponent.lua, not properly passing a number

### ISSUE THREAD

**Issue by 1byte2bytes** [MonchaGames/TestRepo#4]
```
Error: PlayerComponent.lua:28: bad argument #1 to 'setColor' (number expected, got nil)
stack traceback:
    [C]: in function 'setColor'
    PlayerComponent.lua:28: in function 'draw'
    Entity.lua:30: in function 'draw'
    OverworldState.lua:32: in function 'draw'
    StateMachine.lua:42: in function 'draw'
    main.lua:17: in function 'draw'
    [string "boot.lua"]:446: in function <[string "boot.lua"]:413>
    [C]: in function 'xpcall'
```

Reproducible by running the code. I used `/Users/Sidney/Downloads/love.app/Contents/MacOS/love /Users/Sidney/tempgit/TestRepo/`

**Comment by 1byte2bytes** [comment]
Is the PlayerConpoment ever given a color? It does not seem to be given a color anywhere.

**Comment by starryangt** [comment]
That was something muffin added. He did not add in defaults arguments, so it crashes when draw gets nil. Either add in defaults, or just remove that part entirely (which is what I suggest, since it's unnecessary and adds visual clutter).

**Comment by 1byte2bytes** [comment]
Fixed!
